from selenium.webdriver.common.by import By


FIRST_QUESTION = (By.ID, 'accordion__heading-0')
FIRST_QUESTION_ACTIVE = (By. ID, "accordion__panel-0")
SECOND_QUESTION = (By.ID, 'accordion__heading-1')
SECOND_QUESTION_ACTIVE = (By. ID, "accordion__panel-1")
THIRD_QUESTION = (By.ID, 'accordion__heading-2')
THIRD_QUESTION_ACTIVE = (By. ID, "accordion__panel-2")
FOURTH_QUESTION = (By.ID, 'accordion__heading-3')
FOURTH_QUESTION_ACTIVE = (By. ID, "accordion__panel-3")
FIFTH_QUESTION = (By.ID, 'accordion__heading-4')
FIFTH_QUESTION_ACTIVE = (By. ID, "accordion__panel-4")
SIXTH_QUESTION = (By.ID, 'accordion__heading-5')
SIXTH_QUESTION_ACTIVE = (By. ID, "accordion__panel-5")
SEVENTH_QUESTION = (By. ID, 'accordion__heading-6')
SEVENTH_QUESTION_ACTIVE = (By. ID, "accordion__panel-6")
EIGHTH_QUESTION = (By.ID, 'accordion__heading-7')
EIGHTH_QUESTION_ACTIVE = (By. ID, "accordion__panel-7")
SCOOTER_IMG = (By.XPATH, "//img[@src= '/assets/scooter.png']")
SCOOTER_LOGO = (By.XPATH, "//img[@alt='Scooter']")
ORDER_BUTTON = (By.XPATH, "//button[@class='Button_Button__ra12g']")
YANDEX_LOGO = (By.XPATH, "//img[contains(@alt,'Yandex')]")
DZEN_SEARCH_BUTTON = (By.XPATH, "//button[contains(.,'Найти')]")
